// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYN4T1qVT2BhJCG_2Sa-YXjQTif3slaVk',
    appId: '1:41621895287:web:f769b5978805384e696e72',
    messagingSenderId: '41621895287',
    projectId: 'invocations-49de5',
    authDomain: 'invocations-49de5.firebaseapp.com',
    storageBucket: 'invocations-49de5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnAC2-FwyyKpAbnhjOLxdym981zhhYWM',
    appId: '1:41621895287:android:c9907a26fa94465f696e72',
    messagingSenderId: '41621895287',
    projectId: 'invocations-49de5',
    storageBucket: 'invocations-49de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSEdpiJF46urypNHzs1RJEHvC9WeVXVJo',
    appId: '1:41621895287:ios:0381e8763430ee56696e72',
    messagingSenderId: '41621895287',
    projectId: 'invocations-49de5',
    storageBucket: 'invocations-49de5.firebasestorage.app',
    iosBundleId: 'com.example.apil01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSEdpiJF46urypNHzs1RJEHvC9WeVXVJo',
    appId: '1:41621895287:ios:0381e8763430ee56696e72',
    messagingSenderId: '41621895287',
    projectId: 'invocations-49de5',
    storageBucket: 'invocations-49de5.firebasestorage.app',
    iosBundleId: 'com.example.apil01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYN4T1qVT2BhJCG_2Sa-YXjQTif3slaVk',
    appId: '1:41621895287:web:404844250d23764f696e72',
    messagingSenderId: '41621895287',
    projectId: 'invocations-49de5',
    authDomain: 'invocations-49de5.firebaseapp.com',
    storageBucket: 'invocations-49de5.firebasestorage.app',
  );
}
